// Code generated by mockery v2.39.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Hasher is an autogenerated mock type for the Hasher type
type Hasher struct {
	mock.Mock
}

// Check provides a mock function with given fields: stamp, rightPrefix
func (_m *Hasher) Check(stamp string, rightPrefix string) bool {
	ret := _m.Called(stamp, rightPrefix)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(stamp, rightPrefix)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// GenerateRandomPrefixToken provides a mock function with given fields:
func (_m *Hasher) GenerateRandomPrefixToken() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateRandomPrefixToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mint provides a mock function with given fields: prefixToken
func (_m *Hasher) Mint(prefixToken string) (string, error) {
	ret := _m.Called(prefixToken)

	if len(ret) == 0 {
		panic("no return value specified for Mint")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(prefixToken)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(prefixToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(prefixToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHasher creates a new instance of Hasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Hasher {
	mock := &Hasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
